language: node_js
env:
  - CXX=g++-4.8
node_js:
  - '8'
  - '6'
before_install:
  - sudo apt-get update
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
